### ISSUE TITLE
An error occurred when attempting to read the Discord Guild Details: json unmarshal

### ISSUE THREAD

**Issue by Wadimich** [FM1337/FactorioCord#5]
Hello! I've started use your app, it's worked nice, but today at morning it became broken.
it Says in error log only this:
`2017-10-27 07:24:23.170060611 +0200 CEST: An error occurred when attempting to read the Discord Guild
Details: json unmarshal`.

I'm starting bot with start.sh script on Ubuntu 16.04 with Factorio 0.15.37

**Comment by FM1337** [comment]
This is probably due to discord updating their APIs, I'll have to investigate and fix it. Currently busy at the moment but I will have it fixed within a few weeks.

**Comment by Wadimich** [comment]
Builded from myself, working now, apparently, DiscordGo lib was updated.
This issue can be closed

**Comment by FM1337** [comment]
1.3 release fixes the problem
